apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: vault-lab
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
    - k8s/rbac/*.yaml
  helm:
    releases:
    - name: vault
      chartPath: hashicorp/vault
      remote: true
      valuesFiles: ["./helm/vault/values.yaml"]
